<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE productes [
<!ELEMENT productes (producte*)>
<!ELEMENT producte (ratoli|teclat|monitor)>
<!ELEMENT ratoli (#PCDATA)>
<!ATTLIST ratoli codi ID #REQUIRED>
<!ELEMENT monitor (#PCDATA)>
<!ATTLIST monitor codi ID #REQUIRED>
<!ELEMENT teclat (#PCDATA)>
<!ATTLIST teclat codi ID #REQUIRED>
]>
<productes>
    <producte>
        <ratoli codi="r01"> sense fil space </ratoli>
    </producte>
    <producte>
        <teclat codi= "t03">Teclat de colors </teclat>
    </producte>
    <producte>
        <monitor codi="m100">TÃ ctil</monitor>
        <!--Producte no pot esser teclat I monitor.-->
    </producte>
 </productes>