<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE biblioteca [
<!ELEMENT biblioteca (llibre)>
<!ELEMENT llibre (titol, idioma, genere, sense_catalogar?, autor, web?, portada?)>
<!ATTLIST llibre codi ID #REQUIRED>
<!ATTLIST llibre any CDATA >
<!ELEMENT titol (#PCDATA)>
<!ELEMENT idioma (#PCDATA)>
<!ELEMENT genere (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ELEMENT portada (#PCDATA)>
]>


<biblioteca> 
    <llibre codi="LL1"  any="2002"> 
       <titol>El instituto</titol> 
       <idioma>Anglès</idioma> 
       <genere>suspens</genere> 
       <autor>Stephen King</autor> 
       <web>https://www.todostuslibros.com/libros/el-instituto_978-84-01-02235-7</web> 
       <portada>/imatges/elinstituto.gif</portada> 
    </llibre>
    <Llibre codi=LL2> 
       <titol> La ruta infinita</titol></titol> 
       <idioma>Espanyol</idioma> 
       <genere>històrica</genere> 
       <sense_catalogar/> 
       <autor>José Calvo Poyato</autor>
    </llibre> 
 </biblioteca>