=== sirazazel/XMLTestArchives/Practica 4/exercici10.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="institut">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumne" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dades" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nom" type="xs:string" />
                                        <xs:element name="llinatge" type="xs:string" />
                                        <xs:element name="dni" maxOccurs="unbounded">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:totalDigits value="9" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="comentaris" maxOccurs="1" minOccurs="0">
                                <xs:simpleType>
                                    <xs:restriction>
                                        <xs:minLength value="5"></xs:minLength>
                                        <xs:maxLength value="50"></xs:maxLength>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="data_naixement" type="xs:date" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sirazazel/XMLTestArchives/Practica 4/exercici10.xml
<?xml version="1.0"?> 
<institut>xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="exercici10.xsd"
   <alumne data_naixement="1-1-2005"> 
      <dades> 
         <nom>Harry</nom> 
         <llinatges>Potter</llinatges> 
         <dni>411113333</dni> 
      </dades>
      <comentaris>Un poc dispers</comentaris> 
   </alumne> 
   <alumne data_naixement="2-2-1999"> 
      <dades> 
         <nom>Bart</nom> 
         <llinatges>Simpson</llinatges> 
         <dni>566565656</dni> 
      </dades>
      <comentaris>caòtic</comentaris> 
   </alumne> 
   <alumne data_naixement="3-3-1975"> 
      <dades> 
         <nom>Darth</nom> 
         <llinatges>Vader</llinatges> 
         <dni>100000012</dni> 
       </dades>
       <comentaris>Misteriós</comentaris> 
   </alumne> 
</institut>
